Repository qor5/web, pull requests merged in 2024-07, with the labels that each got.

#67 go-plaid-observer && plaid && stateful
  .gitignore
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/package.json
  corejs/pnpm-lock.yaml
  corejs/src/__tests__/app.spec.ts
  corejs/src/__tests__/builder.spec.ts
  corejs/src/__tests__/listener.spec.ts
  corejs/src/__tests__/runscript.spec.ts
  corejs/src/__tests__/scope-change.spec.ts
  corejs/src/__tests__/scope.spec.ts
  corejs/src/__tests__/testutils.ts
  corejs/src/__tests__/utils.spec.ts
  corejs/src/app.ts
  corejs/src/builder.ts
  corejs/src/go-plaid-listener.vue
  corejs/src/go-plaid-run-script.vue
  corejs/src/go-plaid-scope.vue
  corejs/src/types.ts
  corejs/src/utils.ts
  examples/todomvc.go
  examples/todomvc_test.go
  examples/treeview.go
  go.mod
  go.sum
  portal.go
  scope.go
  stateful/action.go
  stateful/dependency.go
  stateful/iface.go
  stateful/query.go
  stateful/query_test.go
  stateful/reload.go
  stateful/sync_query.go
  stateful/utils.go
  vue.go
Labels: size/XXL

#68 fix: caused by the change of dependency center due to the browser path switching
  stateful/action.go
Labels: size/XS

#69 Add t.Run so that cases can be run independently
  examples/todomvc_test.go
Labels: size/XS

#70 parent-size-observer
  corejs/dist/index.js
  corejs/src/app.ts
  corejs/src/parent-size-observer.vue
  vue.go
Labels: size/M

#71 Fix: multipartest body will be reset nil
  multipartestutils/case.go
Labels: size/XS

#72 fix missed unescape && add cache for tags && fix TODOs
  .gitignore
  go.mod
  go.sum
  stateful/query.go
  stateful/query_test.go
  stateful/utils.go
Labels: size/L
