Repository qor5/web, pull requests merged in 2024-09, with the labels that each got.

#87 chore: update the version of vue
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/package.json
  corejs/pnpm-lock.yaml
Labels: size/XXL

#88 add slug method for plaid && remove wrappedComputed
  corejs/dist/index.js
  corejs/package.json
  corejs/pnpm-lock.yaml
  corejs/src/__tests__/utils.spec.ts
  corejs/src/builder.ts
  corejs/src/lifecycle.ts
  corejs/src/utils.ts
Labels: size/L

#91 Support validationGlobalError
  validation_error.go
  validation_error_test.go
Labels: size/M

#92 add web.GetEventContext
  api.go
Labels: size/XS

#93 fix: close progress bar when ajax is error
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/src/app.ts
  corejs/src/builder.ts
  corejs/src/fetchInterceptor.ts
Labels: size/XL

#94 fix: fix fetchInterceptor error
  corejs/dist/index.js
  corejs/src/builder.ts
  corejs/src/fetchInterceptor.ts
Labels: size/L

#95 fix: clear requestMap whenever exists onResponse hook
  corejs/dist/index.js
  corejs/src/fetchInterceptor.ts
Labels: size/XS
