Repository qor5/web, pull requests merged in 2024-06, with the labels that each got.

#58 fix debounce before assign
  corejs/dist/index.js
  corejs/src/__tests__/portal.spec.ts
  corejs/src/go-plaid-scope.vue
Labels: size/S

#49 add test for case where pagefunc returns nil body
  page_test.go
Labels: size/XS

#60 add notification support
  corejs/dist/index.js
  corejs/src/__tests__/scope-change.spec.ts
  corejs/src/app.ts
  corejs/src/go-plaid-scope.vue
  corejs/src/utils.ts
  go.mod
  go.sum
  scope.go
Labels: size/L

#59 Add codecov
  .github/workflows/go.yml
Labels: size/XS

#61 notification.id generated by the frontend
  corejs/dist/index.js
  corejs/pnpm-lock.yaml
  corejs/src/__tests__/scope-change.spec.ts
  corejs/src/app.ts
  go.mod
  go.sum
  scope.go
Labels: size/XXL

#63 Fix w.body be closed unexceptedly
  multipartestutils/case.go
Labels: size/XS

#64 stateful
  .github/workflows/go.yml
  .gitignore
  api.go
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/package.json
  corejs/pnpm-lock.yaml
  corejs/src/__tests__/assign.spec.ts
  corejs/src/app.ts
  corejs/src/assign.ts
  examples/composite-components.go
  examples/event-handling.go
  examples/form-handling.go
  examples/hello-button.go
  examples/hello-world-reload.go
  examples/hello-world.go
  examples/manipulate-page-url.go
  examples/mux.go
  examples/page-transition.go
  examples/partial-reload.go
  examples/partial-update.go
  examples/reload-with-a-flash.go
  examples/server/main.go
  examples/shortcut.go
  examples/storage.go
  examples/todomvc.go
  examples/todomvc_test.go
  examples/treeview.go
  examples/type-safe-builder-sample.go
  examples/utils.go
  examples/web-scope.go
  go.mod
  go.sum
  page.go
  scope.go
  stateful/action.go
  stateful/dependency.go
  stateful/iface.go
  stateful/reload.go
  stateful/sync_query.go
  stateful/utils.go
Labels: size/XXL

#65 scope: add test case to operate parent locals
  .github/workflows/corejs.yml
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/package.json
  corejs/pnpm-lock.yaml
  corejs/src/__tests__/scope.spec.ts
  corejs/src/go-plaid-portal.vue
Labels: size/L
