Repository qor5/web, pull requests merged in 2024-08, with the labels that each got.

#73 feat: Add ParamAsBool function
  api.go
Labels: size/XS

#74 fix: use window.location.href when event.state is null at onpopstate
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/src/app.ts
  corejs/src/builder.ts
Labels: size/XXL

#76 lifecycle directives && rm go-plaid-run-script && plaid: add lodash && v-run => v-on-mounted
  corejs/dist/index.js
  corejs/dist/vue.global.dev.js
  corejs/dist/vue.global.prod.js
  corejs/src/__tests__/assign.spec.ts
  corejs/src/__tests__/builder.spec.ts
  corejs/src/__tests__/runscript.spec.ts
  corejs/src/__tests__/scope.spec.ts
  corejs/src/app.ts
  corejs/src/assign.ts
  corejs/src/builder.ts
  corejs/src/go-plaid-listener.vue
  corejs/src/go-plaid-portal.vue
  corejs/src/go-plaid-run-script.vue
  corejs/src/lifecycle.ts
  examples/hello-button.go
  examples/hello-button_test.go
  examples/todomvc.go
  stateful/action.go
  vue.go
Labels: size/L

#77 add unexpect ignore test file
  .gitignore
  corejs/src/__tests__/lifecycle.spec.ts
Labels: size/M

#75 Add examples test for more coverage
  cov.sh
  examples/examples_test.go
  page.go
Labels: size/L

#78 feat: To distinguish between page loads and regular AJAX requests, an…
  corejs/dist/index.js
  corejs/package.json
  corejs/pnpm-lock.yaml
  corejs/src/app.ts
  corejs/src/fetchInterceptor.ts
Labels: size/L

#80 fix: fetch wrap breaks the test case
  corejs/src/app.ts
  corejs/src/fetchInterceptor.ts
Labels: size/S

#79 add history manager && prevent pushState on the same path
  .gitignore
  build.sh
  corejs/dist/index.js
  corejs/src/__tests__/app.spec.ts
  corejs/src/__tests__/builder.spec.ts
  corejs/src/__tests__/history.spec.ts
  corejs/src/__tests__/utils.spec.ts
  corejs/src/app.ts
  corejs/src/builder.ts
  corejs/src/fetchInterceptor.ts
  corejs/src/history.ts
  corejs/src/utils.ts
Labels: size/L

#81 use `beforeFetch` to prevent `form` from being modified
  corejs/dist/index.js
  corejs/src/__tests__/builder.spec.ts
  corejs/src/builder.ts
  stateful/action.go
  vue.go
Labels: size/M

#82 feat: make progressBar build-in in front-end
  corejs/dist/index.js
  corejs/package.json
  corejs/src/app.ts
  corejs/src/fetchInterceptor.ts
  corejs/src/progressBarCtrl.ts
  corejs/src/utils.ts
Labels: size/L

#83 perf: sync the progress bar increasement with rendering in low speed network
  corejs/dist/index.js
  corejs/src/fetchInterceptor.ts
  corejs/src/progressBarCtrl.ts
Labels: size/M

#84 lifecycle: directives auto stop watch on unmounted
  corejs/dist/index.js
  corejs/src/__tests__/lifecycle.spec.ts
  corejs/src/lifecycle.ts
Labels: size/L

#85 lifecycle: add `computed`
  corejs/dist/index.js
  corejs/src/__tests__/lifecycle.spec.ts
  corejs/src/lifecycle.ts
Labels: size/M

#86 improve test `portal auto reload` to prevent occasional error
  corejs/src/__tests__/portal.spec.ts
Labels: size/XS
